services:
  - type: web
    plan: free
    name: kulot-friends-chat
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 --threads 100 app:app
    healthCheckPath: /health
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: INVITE_CODE
        sync: false
      - key: COOKIE_SECURE
        value: "true"